export const CHANGE_SHOPPING_DATA = 'CHANGE_SHOPPING_DATA'
export const CHANGE_STAR_COLOR = 'CHANGE_STAR_COLOR'
// export const CHANGE_STAR_COLOR_TO_WHITE = 'CHANGE_STAR_COLOR_TO_WHITE'
export const ADD_COLLECT_ITEM_LIST = 'ADD_COLLECT_ITEM_LIST'
export const REMOVE_COLLECT_ITEM_LIST = 'REMOVE_COLLECT_ITEM_LIST'

